# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20170207_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, help_text='500x500px', upload_to='quzi', verbose_name='Ссылка картинки'),
        ),
    ]
