# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, help_text='500x500px', upload_to='article', verbose_name='Ссылка картинки'),
        ),
    ]
