# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slaider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaider',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='sratic/media/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
