# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170221_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaider',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='', verbose_name='Ссылка картинки'),
        ),
    ]
