# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170221_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_content', models.TextField()),
                ('news_image', models.ImageField(blank=True, help_text='500x500px', upload_to='', verbose_name='Ссылка картинки')),
            ],
        ),
        migrations.DeleteModel(
            name='Slaider',
        ),
    ]
