# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170222_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
