# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_news_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_image',
            field=models.ImageField(blank=True, help_text='900x500px', upload_to='', verbose_name='Ссылка картинки'),
        ),
    ]
