# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='metadata_title',
            field=models.CharField(blank=True, help_text='Заголовок страницы', max_length=200, verbose_name='Заголовок'),
        ),
    ]
