# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20170223_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='metadata_date',
            field=models.DateTimeField(auto_now=True, help_text='дата последнего изменения', verbose_name='дата изменения'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='metadata_image',
            field=models.ImageField(blank=True, help_text='900x500px', upload_to='', verbose_name='Ссылка картинки'),
        ),
    ]
