# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170224_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='metadata_url',
            field=models.CharField(default=1, help_text='aдрес страницы', max_length=200, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='metadata_name',
            field=models.CharField(help_text='имя отображаемое в меню', max_length=200, verbose_name='имя страницы'),
        ),
    ]
