# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0002_auto_20170207_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(max_length=200)),
                ('question_content', models.TextField()),
                ('question_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.TableOfContents')),
            ],
        ),
    ]
