# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quzi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansver_content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='question_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quzi.Question'),
        ),
    ]
