# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quzi', '0002_auto_20170210_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='ansver_boolean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
    ]
