# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quzi', '0003_auto_20170210_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_list_title', models.CharField(max_length=200, verbose_name='Название теста')),
                ('question_list_content', models.CharField(max_length=500, verbose_name='Описание теста')),
            ],
            options={
                'db_table': 'question_list',
            },
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_article',
        ),
        migrations.AlterField(
            model_name='answer',
            name='ansver_boolean',
            field=models.BooleanField(default=False, verbose_name='Верный ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ansver_content',
            field=models.TextField(verbose_name='Текст ответа'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.TextField(verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_title',
            field=models.CharField(max_length=200, verbose_name='Заголовок вопроса'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_question_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quzi.QuestionList'),
            preserve_default=False,
        ),
    ]
