# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-11 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quzi', '0004_auto_20170211_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_title',
        ),
    ]
