# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quzi', '0005_remove_question_question_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_test', models.TextField(verbose_name='Коментарий к тесту')),
                ('procent', models.SmallIntegerField(verbose_name='Процент при котором выводится коментарий')),
            ],
            options={
                'db_table': 'Comments',
            },
        ),
    ]
