# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quzi', '0008_auto_20170220_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_article_url',
        ),
        migrations.AddField(
            model_name='questionlist',
            name='question_list_article_url',
            field=models.URLField(blank=True, choices=[('/article/1/', 'Тема №1'), ('/article/2/', 'Основы физики'), ('/article/3/', 'dfgfdg')], default=False),
        ),
    ]
