# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quzi', '0013_auto_20170221_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionlist',
            name='question_list_article_url',
        ),
    ]
